In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("DateFruit_Dataset.csv")

In [3]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [4]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [5]:
df.shape

(898, 35)

In [6]:
X = df.drop("Class", axis=1)
y = df["Class"]

In [7]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [8]:
X.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [9]:
#Data Standardization 
from sklearn.preprocessing import StandardScaler, LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
# y

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

In [12]:
X_train
X_test

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
331,143957,1452.2620,523.1368,352.3305,0.7392,428.1259,0.9844,146236,0.7746,1.4848,...,-0.3565,4.1478,3.4278,2.4134,-36987568128,-34249711616,-23752157184,77.3446,75.2287,62.9057
638,260563,1975.3740,762.5055,437.8510,0.8187,575.9854,0.9871,263977,0.6648,1.7415,...,0.3581,7.7778,16.2644,3.6606,-2424508160,-4791147520,-8197618688,16.2304,22.3860,28.8860
326,154245,1503.5980,546.4366,361.8018,0.7494,443.1601,0.9883,156070,0.7420,1.5103,...,0.3657,2.4202,2.9624,3.0045,-14960579584,-14010061824,-14057613312,48.2049,46.8561,46.4054
848,317794,2280.9690,875.5868,525.3380,0.8000,636.1037,0.9016,352462,0.6484,1.6667,...,0.3719,2.2682,2.1522,2.9676,-47417053184,-39451316224,-33127270400,58.7696,54.0476,50.8977
39,402279,2295.8630,798.9365,643.2753,0.5931,715.6797,0.9936,404887,0.7867,1.2420,...,1.9477,5.5889,12.5304,9.9496,-30746945536,-32178810880,-35126345728,43.7705,45.6162,46.3010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,283770,2096.7639,775.8751,468.8516,0.7968,601.0883,0.9737,291436,0.6751,1.6548,...,0.8440,11.0456,12.1213,6.1299,-4560918528,-7281993216,-9060293632,20.5245,25.8721,29.4805
25,381508,2239.7891,734.2203,666.2502,0.4202,696.9584,0.9919,384642,0.7398,1.1020,...,2.0740,6.6729,10.5392,9.3474,-25635362816,-25228310528,-28113027072,41.0071,41.1774,41.5364
84,253276,1961.0400,740.2677,437.3487,0.8068,567.8741,0.9822,257864,0.7493,1.6926,...,-0.1425,2.0920,1.9879,2.1549,-45574098944,-41109114880,-35898662912,64.4454,61.4443,58.3921
10,364495,2216.4900,790.9014,590.7698,0.6649,681.2411,0.9949,366374,0.7658,1.3388,...,0.9283,3.0514,4.3653,6.0898,-41679380480,-40727969792,-37574615040,52.7269,52.9888,50.3108
332,156030,1566.9790,595.6793,384.2388,0.7641,445.7169,0.9118,171132,0.6319,1.5503,...,-0.3529,2.5952,2.3904,2.6668,-33837977600,-33563627520,-25646532608,70.7212,71.3609,63.4659

In [13]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

###  ANN

In [14]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [15]:
X_train_tensor = torch.tensor(X_train_scaled, dtype = torch.float32)
y_train_tensor = torch.tensor(y_train, dtype = torch.long)

X_test_tensor = torch.tensor(X_test_scaled, dtype = torch.float32)
y_test_tensor = torch.tensor(y_test, dtype = torch.long)

In [16]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [17]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=32)
test_loader = DataLoader(test_dataset, batch_size=32)

### Model Building

In [22]:
# build uor model
class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()

        self.model = nn.Sequential(
            nn.Linear(X.shape[1], 64),
            nn.ReLU(),
            nn.Linear(64,64),
            nn.ReLU(),
            nn.Linear(64,7)
        )
    def forward(self, x):
        return self.model(x)

In [26]:
model = ANN()

#loss and optimizer
criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

### Training the neural Network (NN)

In [27]:
epochs = 100
for epoch in range(epochs):
    model.train()

    running_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()

        outputs = model(xb)
        loss = criteria(outputs, yb)
        loss.backward()
        optimizer.step()    #params update

        running_loss += loss

    train_loss = running_loss / len(train_loader)

    print(f"epoch = {epoch+1}/{epochs}, loss = {train_loss}")

epoch = 1/100, loss = 1.7495101690292358
epoch = 2/100, loss = 1.1496940851211548
epoch = 3/100, loss = 0.7528225183486938
epoch = 4/100, loss = 0.5657171607017517
epoch = 5/100, loss = 0.45606982707977295
epoch = 6/100, loss = 0.39336779713630676
epoch = 7/100, loss = 0.35391750931739807
epoch = 8/100, loss = 0.324003666639328
epoch = 9/100, loss = 0.28491008281707764
epoch = 10/100, loss = 0.2652912437915802
epoch = 11/100, loss = 0.25244584679603577
epoch = 12/100, loss = 0.23400306701660156
epoch = 13/100, loss = 0.21404631435871124
epoch = 14/100, loss = 0.20933866500854492
epoch = 15/100, loss = 0.19330845773220062
epoch = 16/100, loss = 0.19852261245250702
epoch = 17/100, loss = 0.17771461606025696
epoch = 18/100, loss = 0.16887351870536804
epoch = 19/100, loss = 0.16920778155326843
epoch = 20/100, loss = 0.15351128578186035
epoch = 21/100, loss = 0.15440614521503448
epoch = 22/100, loss = 0.14710675179958344
epoch = 23/100, loss = 0.14119316637516022
epoch = 24/100, loss = 0.14067989587783813
epoch = 25/100, loss = 0.13882391154766083
epoch = 26/100, loss = 0.1292245090007782
epoch = 27/100, loss = 0.1272788941860199
epoch = 28/100, loss = 0.12016179412603378
epoch = 29/100, loss = 0.11938925087451935
epoch = 30/100, loss = 0.11643878370523453
epoch = 31/100, loss = 0.11791679263114929
epoch = 32/100, loss = 0.11212562769651413
epoch = 33/100, loss = 0.10781479626893997
epoch = 34/100, loss = 0.10880155116319656
epoch = 35/100, loss = 0.11027243733406067
epoch = 36/100, loss = 0.1079140156507492
epoch = 37/100, loss = 0.09944304078817368
epoch = 38/100, loss = 0.10167250782251358
epoch = 39/100, loss = 0.09222552180290222
epoch = 40/100, loss = 0.09746009111404419
epoch = 41/100, loss = 0.08758462965488434
epoch = 42/100, loss = 0.1061692163348198
epoch = 43/100, loss = 0.09598132967948914
epoch = 44/100, loss = 0.08864455670118332
epoch = 45/100, loss = 0.08666090667247772
epoch = 46/100, loss = 0.08148583024740219
epoch = 47/100, loss = 0.0778491273522377
epoch = 48/100, loss = 0.0809047669172287
epoch = 49/100, loss = 0.08826512098312378
epoch = 50/100, loss = 0.07420569658279419
epoch = 51/100, loss = 0.07579439133405685
epoch = 52/100, loss = 0.07364796847105026
epoch = 53/100, loss = 0.07470937818288803
epoch = 54/100, loss = 0.07232661545276642
epoch = 55/100, loss = 0.0684855729341507
epoch = 56/100, loss = 0.06961923837661743
epoch = 57/100, loss = 0.06772071123123169
epoch = 58/100, loss = 0.06849478930234909
epoch = 59/100, loss = 0.0689813569188118
epoch = 60/100, loss = 0.06279970705509186
epoch = 61/100, loss = 0.06115315854549408
epoch = 62/100, loss = 0.06286358833312988
epoch = 63/100, loss = 0.05832940712571144
epoch = 64/100, loss = 0.05637417733669281
epoch = 65/100, loss = 0.05657941475510597
epoch = 66/100, loss = 0.05307255685329437
epoch = 67/100, loss = 0.05111270397901535
epoch = 68/100, loss = 0.049622029066085815
epoch = 69/100, loss = 0.059420689940452576
epoch = 70/100, loss = 0.0720958337187767
epoch = 71/100, loss = 0.05334736034274101
epoch = 72/100, loss = 0.04733872041106224
epoch = 73/100, loss = 0.04480063542723656
epoch = 74/100, loss = 0.04411260411143303
epoch = 75/100, loss = 0.04271858558058739
epoch = 76/100, loss = 0.042252492159605026
epoch = 77/100, loss = 0.04364004358649254
epoch = 78/100, loss = 0.04124797508120537
epoch = 79/100, loss = 0.04868647828698158
epoch = 80/100, loss = 0.05014915391802788
epoch = 81/100, loss = 0.04871268942952156
epoch = 82/100, loss = 0.040562864392995834
epoch = 83/100, loss = 0.036685552448034286
epoch = 84/100, loss = 0.034621354192495346
epoch = 85/100, loss = 0.03280757740139961
epoch = 86/100, loss = 0.03594251349568367
epoch = 87/100, loss = 0.03435467183589935
epoch = 88/100, loss = 0.033676955848932266
epoch = 89/100, loss = 0.03161998838186264
epoch = 90/100, loss = 0.03045445680618286
epoch = 91/100, loss = 0.028944456949830055
epoch = 92/100, loss = 0.03493586555123329
epoch = 93/100, loss = 0.032395265996456146
epoch = 94/100, loss = 0.02699945494532585
epoch = 95/100, loss = 0.02816222794353962
epoch = 96/100, loss = 0.029895225539803505
epoch = 97/100, loss = 0.025675110518932343
epoch = 98/100, loss = 0.024113500490784645
epoch = 99/100, loss = 0.024514004588127136
epoch = 100/100, loss = 0.02405603602528572

### Model Evaluation

In [32]:
model.eval()

total = 0
correct = 0

with torch.no_grad():
    for xb, yb in test_loader:
        outputs = model(xb)   # [0.2,0.5,1.3,-0.5,..]  - 7 vals
        _, predicted = torch.max(outputs, 1)

        correct += (predicted == yb). sum().item()
        total += yb.size(0)   # actual samples in each batch

print("total vals : ", total)
print("correct vals : ", correct)
print("accuracy : ", correct/total * 100)

total vals :  180
correct vals :  170
accuracy :  94.44444444444444

In [30]:
y_test.shape

(180,)